#############################################################################
# Makefile for building: libQArtNet.1.0.0.dylib
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  QArtNet.pro
# Template: lib
# Command: /Users/ruibarreiros/Qt/5.7/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile QArtNet.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQARTNET_LIBRARY -DQT_QML_DEBUG -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.8 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.8 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../../../../Qt/5.7/clang_64/lib/QtNetwork.framework/Headers -I../../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers -I. -I../../../../Qt/5.7/clang_64/mkspecs/macx-clang -F/Users/ruibarreiros/Qt/5.7/clang_64/lib
QMAKE         = /Users/ruibarreiros/Qt/5.7/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = QArtNet1.0.0
DISTDIR = /Users/ruibarreiros/Documents/Projectos/Luz/QArtNet/.tmp/QArtNet1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.8 -Wl,-rpath,/Users/ruibarreiros/Qt/5.7/clang_64/lib -single_module -dynamiclib -compatibility_version	1.0 -current_version	1.0.0 -install_name	libQArtNet.1.dylib
LIBS          = $(SUBLIBS) -F/Users/ruibarreiros/Qt/5.7/clang_64/lib -framework QtNetwork -framework QtCore -framework DiskArbitration -framework IOKit 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = qartnet.cpp \
		qartnetnode.cpp \
		qartnetpoll.cpp moc_qartnet.cpp \
		moc_qartnetnode.cpp \
		moc_qartnetpoll.cpp
OBJECTS       = qartnet.o \
		qartnetnode.o \
		qartnetpoll.o \
		moc_qartnet.o \
		moc_qartnetnode.o \
		moc_qartnetpoll.o
DIST          = ../../../../Qt/5.7/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt/5.7/clang_64/mkspecs/qdevice.pri \
		../../../../Qt/5.7/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt/5.7/clang_64/mkspecs/common/unix.conf \
		../../../../Qt/5.7/clang_64/mkspecs/common/mac.conf \
		../../../../Qt/5.7/clang_64/mkspecs/common/macx.conf \
		../../../../Qt/5.7/clang_64/mkspecs/common/sanitize.conf \
		../../../../Qt/5.7/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt/5.7/clang_64/mkspecs/common/clang.conf \
		../../../../Qt/5.7/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Qt/5.7/clang_64/mkspecs/qconfig.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt/5.7/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Qt/5.7/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/5.7/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../Qt/5.7/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt/5.7/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt/5.7/clang_64/mkspecs/features/qml_debug.prf \
		../../../../Qt/5.7/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt/5.7/clang_64/mkspecs/features/qt.prf \
		../../../../Qt/5.7/clang_64/mkspecs/features/resources.prf \
		../../../../Qt/5.7/clang_64/mkspecs/features/moc.prf \
		../../../../Qt/5.7/clang_64/mkspecs/features/unix/thread.prf \
		../../../../Qt/5.7/clang_64/mkspecs/features/file_copies.prf \
		../../../../Qt/5.7/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt/5.7/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt/5.7/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt/5.7/clang_64/mkspecs/features/lex.prf \
		QArtNet.pro qartnet.h \
		qartnet_global.h \
		qartnetnode.h \
		common.h \
		qartnetpoll.h qartnet.cpp \
		qartnetnode.cpp \
		qartnetpoll.cpp
QMAKE_TARGET  = QArtNet
DESTDIR       = 
TARGET        = libQArtNet.1.0.0.dylib
TARGETA       = libQArtNet.a
TARGET0       = libQArtNet.dylib
TARGETD       = libQArtNet.1.0.0.dylib
TARGET1       = libQArtNet.1.dylib
TARGET2       = libQArtNet.1.0.dylib


first: all
####### Build rules

$(TARGET):  $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	-$(DEL_FILE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-ln -s $(TARGET) $(TARGET0)
	-ln -s $(TARGET) $(TARGET1)
	-ln -s $(TARGET) $(TARGET2)



staticlib: $(TARGETA)

$(TARGETA):  $(OBJECTS) $(OBJCOMP) 
	-$(DEL_FILE) $(TARGETA) 
	$(AR) $(TARGETA) $(OBJECTS)
	$(RANLIB) $(TARGETA)

Makefile: QArtNet.pro ../../../../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf ../../../../Qt/5.7/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt/5.7/clang_64/mkspecs/qdevice.pri \
		../../../../Qt/5.7/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt/5.7/clang_64/mkspecs/common/unix.conf \
		../../../../Qt/5.7/clang_64/mkspecs/common/mac.conf \
		../../../../Qt/5.7/clang_64/mkspecs/common/macx.conf \
		../../../../Qt/5.7/clang_64/mkspecs/common/sanitize.conf \
		../../../../Qt/5.7/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt/5.7/clang_64/mkspecs/common/clang.conf \
		../../../../Qt/5.7/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Qt/5.7/clang_64/mkspecs/qconfig.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt/5.7/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt/5.7/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Qt/5.7/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/5.7/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../Qt/5.7/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt/5.7/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt/5.7/clang_64/mkspecs/features/qml_debug.prf \
		../../../../Qt/5.7/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt/5.7/clang_64/mkspecs/features/qt.prf \
		../../../../Qt/5.7/clang_64/mkspecs/features/resources.prf \
		../../../../Qt/5.7/clang_64/mkspecs/features/moc.prf \
		../../../../Qt/5.7/clang_64/mkspecs/features/unix/thread.prf \
		../../../../Qt/5.7/clang_64/mkspecs/features/file_copies.prf \
		../../../../Qt/5.7/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt/5.7/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt/5.7/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt/5.7/clang_64/mkspecs/features/lex.prf \
		QArtNet.pro \
		../../../../Qt/5.7/clang_64/lib/QtNetwork.framework/QtNetwork.prl \
		../../../../Qt/5.7/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile QArtNet.pro
../../../../Qt/5.7/clang_64/mkspecs/features/spec_pre.prf:
../../../../Qt/5.7/clang_64/mkspecs/qdevice.pri:
../../../../Qt/5.7/clang_64/mkspecs/features/device_config.prf:
../../../../Qt/5.7/clang_64/mkspecs/common/unix.conf:
../../../../Qt/5.7/clang_64/mkspecs/common/mac.conf:
../../../../Qt/5.7/clang_64/mkspecs/common/macx.conf:
../../../../Qt/5.7/clang_64/mkspecs/common/sanitize.conf:
../../../../Qt/5.7/clang_64/mkspecs/common/gcc-base.conf:
../../../../Qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../../Qt/5.7/clang_64/mkspecs/common/clang.conf:
../../../../Qt/5.7/clang_64/mkspecs/common/clang-mac.conf:
../../../../Qt/5.7/clang_64/mkspecs/qconfig.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_charts.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../Qt/5.7/clang_64/mkspecs/features/qt_functions.prf:
../../../../Qt/5.7/clang_64/mkspecs/features/qt_config.prf:
../../../../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf:
../../../../Qt/5.7/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../../Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf:
../../../../Qt/5.7/clang_64/mkspecs/features/default_pre.prf:
../../../../Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf:
../../../../Qt/5.7/clang_64/mkspecs/features/resolve_config.prf:
../../../../Qt/5.7/clang_64/mkspecs/features/default_post.prf:
../../../../Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf:
../../../../Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf:
../../../../Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf:
../../../../Qt/5.7/clang_64/mkspecs/features/qml_debug.prf:
../../../../Qt/5.7/clang_64/mkspecs/features/warn_on.prf:
../../../../Qt/5.7/clang_64/mkspecs/features/qt.prf:
../../../../Qt/5.7/clang_64/mkspecs/features/resources.prf:
../../../../Qt/5.7/clang_64/mkspecs/features/moc.prf:
../../../../Qt/5.7/clang_64/mkspecs/features/unix/thread.prf:
../../../../Qt/5.7/clang_64/mkspecs/features/file_copies.prf:
../../../../Qt/5.7/clang_64/mkspecs/features/mac/rez.prf:
../../../../Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf:
../../../../Qt/5.7/clang_64/mkspecs/features/exceptions.prf:
../../../../Qt/5.7/clang_64/mkspecs/features/yacc.prf:
../../../../Qt/5.7/clang_64/mkspecs/features/lex.prf:
QArtNet.pro:
../../../../Qt/5.7/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
../../../../Qt/5.7/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile QArtNet.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents qartnet.h qartnet_global.h qartnetnode.h common.h qartnetpoll.h $(DISTDIR)/
	$(COPY_FILE) --parents qartnet.cpp qartnetnode.cpp qartnetpoll.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) $(TARGET0) $(TARGET1) $(TARGET2) $(TARGETA)
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_qartnet.cpp moc_qartnetnode.cpp moc_qartnetpoll.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_qartnet.cpp moc_qartnetnode.cpp moc_qartnetpoll.cpp
moc_qartnet.cpp: qartnet_global.h \
		common.h \
		qartnetnode.h \
		../../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../../Qt/5.7/clang_64/lib/QtNetwork.framework/Headers/QHostAddress \
		../../../../Qt/5.7/clang_64/lib/QtNetwork.framework/Headers/qhostaddress.h \
		qartnetpoll.h \
		qartnet.h \
		../../../../Qt/5.7/clang_64/bin/moc
	/Users/ruibarreiros/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/ruibarreiros/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/ruibarreiros/Documents/Projectos/Luz/QArtNet -I/Users/ruibarreiros/Qt/5.7/clang_64/lib/QtNetwork.framework/Headers -I/Users/ruibarreiros/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.3.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include -I'/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks (framework directory)' -F/Users/ruibarreiros/Qt/5.7/clang_64/lib qartnet.h -o moc_qartnet.cpp

moc_qartnetnode.cpp: qartnet_global.h \
		common.h \
		../../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../../Qt/5.7/clang_64/lib/QtNetwork.framework/Headers/QHostAddress \
		../../../../Qt/5.7/clang_64/lib/QtNetwork.framework/Headers/qhostaddress.h \
		qartnetnode.h \
		../../../../Qt/5.7/clang_64/bin/moc
	/Users/ruibarreiros/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/ruibarreiros/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/ruibarreiros/Documents/Projectos/Luz/QArtNet -I/Users/ruibarreiros/Qt/5.7/clang_64/lib/QtNetwork.framework/Headers -I/Users/ruibarreiros/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.3.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include -I'/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks (framework directory)' -F/Users/ruibarreiros/Qt/5.7/clang_64/lib qartnetnode.h -o moc_qartnetnode.cpp

moc_qartnetpoll.cpp: ../../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		qartnetpoll.h \
		../../../../Qt/5.7/clang_64/bin/moc
	/Users/ruibarreiros/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/ruibarreiros/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/ruibarreiros/Documents/Projectos/Luz/QArtNet -I/Users/ruibarreiros/Qt/5.7/clang_64/lib/QtNetwork.framework/Headers -I/Users/ruibarreiros/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.3.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include -I'/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks (framework directory)' -F/Users/ruibarreiros/Qt/5.7/clang_64/lib qartnetpoll.h -o moc_qartnetpoll.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

qartnet.o: qartnet.cpp qartnet.h \
		qartnet_global.h \
		common.h \
		qartnetnode.h \
		../../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../../Qt/5.7/clang_64/lib/QtNetwork.framework/Headers/QHostAddress \
		../../../../Qt/5.7/clang_64/lib/QtNetwork.framework/Headers/qhostaddress.h \
		qartnetpoll.h \
		../../../../Qt/5.7/clang_64/lib/QtNetwork.framework/Headers/QUdpSocket \
		../../../../Qt/5.7/clang_64/lib/QtNetwork.framework/Headers/qudpsocket.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qartnet.o qartnet.cpp

qartnetnode.o: qartnetnode.cpp qartnetnode.h \
		qartnet_global.h \
		common.h \
		../../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../../Qt/5.7/clang_64/lib/QtNetwork.framework/Headers/QHostAddress \
		../../../../Qt/5.7/clang_64/lib/QtNetwork.framework/Headers/qhostaddress.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qartnetnode.o qartnetnode.cpp

qartnetpoll.o: qartnetpoll.cpp qartnetpoll.h \
		../../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qartnetpoll.o qartnetpoll.cpp

moc_qartnet.o: moc_qartnet.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qartnet.o moc_qartnet.cpp

moc_qartnetnode.o: moc_qartnetnode.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qartnetnode.o moc_qartnetnode.cpp

moc_qartnetpoll.o: moc_qartnetpoll.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qartnetpoll.o moc_qartnetpoll.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/usr/lib || mkdir -p $(INSTALL_ROOT)/usr/lib
	-$(INSTALL_PROGRAM) $(TARGET) $(INSTALL_ROOT)/usr/lib/$(TARGET)
	-$(SYMLINK) $(TARGET) $(INSTALL_ROOT)/usr/lib/$(TARGET0)
	-$(SYMLINK) $(TARGET) $(INSTALL_ROOT)/usr/lib/$(TARGET1)
	-$(SYMLINK) $(TARGET) $(INSTALL_ROOT)/usr/lib/$(TARGET2)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/usr/lib/$(TARGET) 
	 -$(DEL_FILE) $(INSTALL_ROOT)/usr/lib/$(TARGET0) 
	 -$(DEL_FILE) $(INSTALL_ROOT)/usr/lib/$(TARGET1) 
	 -$(DEL_FILE) $(INSTALL_ROOT)/usr/lib/$(TARGET2)
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/lib/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

